version: "3.8"
services:
  mojosdk:
    image: mojosdk
    build:
      dockerfile: ./Dockerfile.mojosdk
    container_name: mojosdk
    tty: true
    stdin_open: true
    ports:
      - 8888:8888
    volumes:
      - ../../:/mojo
    restart: unless-stopped
    # entrypoint: /bin/bash
    deploy:
      # resources:
      #   limits:
      #     cpus: '6'
