[project]
name = "Mojo"
authors = ["Modular <hello@modular.com>"]
channels = ["conda-forge", "https://conda.modular.com/max/"]
platforms = ["linux-64", "linux-aarch64", "osx-arm64"]

[tasks]
tests ="./stdlib/scripts/run-tests.sh"
examples = "./examples/run-examples.sh"
benchmarks = { cmd = ["./stdlib/scripts/run-benchmarks.sh"], env = { MODULAR_MOJO_NIGHTLY_IMPORT_PATH = "$CONDA_PREFIX/lib/mojo" } }

[dependencies]
python = ">=3.12.8,<3.13"
lit = ">=19.1.7,<20"
max = ">=24.6.0,<25"
